language: minimal
dist: bionic
script: sudo ./build.sh
deploy:
  provider: releases
  api_key:
    secure: J4IPzwXNfaSkCq+ry8VfScIdu+7ERf+P84ltQVyRtz63AJ9XpWEgWS8w49ryEGKPvKYy4/MRByuVzX2lMajuvd5+P4aFzKrIusLomK0uIy7J5gZJkW//YnUY7sZBV/oMQgr558m1mPKJ4adj+jklRz11itEvjKYdfcb1rO/d0+onPFAJdjtTx2829JvdFVfvOYYH/HFV93O///z0irW73L+wQv8k6uzpGrTCOyI4TzlvwOtUUDx3wR14F2CMEVX9d9dl3L865pJxI09ScA3LP2dgzADhFh0Nqm5JjLmKBI3xnYvj2t6HgDrQrubHFRp863DOgY0CJ0KwyuNNE2Ke+yR6QY9upsPKVJB/KhqJ4Bm3No5nfNJa/JQTGsk4jThosXxw9py7bapIVT++mgk050fWtFhl36bHJm4nw3DoLvHdOVKVfH0vuaCXecHECSjxg0LiUPlOnRIP5B1PBJPf5oATZYY5uMfJCep9B5Zx09wdbh+Z/jrlyQCBiYXeSzmtrjor6P0deX4Wo9kbQhV4yfaVdoeiGabJ66uM6IGZHP/nsjn8+PYlnT62KKgmnMAWOf4sTlTEiZR7frhj7oIS8iGu2IDauFgz0+Cf+QQtQTN3SHStn6jh6fob2Xgs4bodDeQlUKvyBNFZ49u6vnZcY6PfdV50H25yvKo4I0N/ZT4=
  file: build/bootloader-*.tar.gz
  file_glob: true
  draft: true
  on:
    repo: Netflix-Skunkworks/s3-flash-bootloader
